name: pipeline-deploy-s3

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install pandoc
      - run: pandoc README.md -f markdown -t html -s -o index.html
      - run: ls -la  # Verifique se o arquivo index.html foi criado
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: index.html  # Faz o upload do arquivo gerado como artefato

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_EC2_METADATA_DISABLED: true
      BUCKET_S3: ${{ vars.BUCKET_S3 }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site
          path: ./  # Baixa o artefato no diretório atual
      - run: ls -la  # Verifique se o arquivo foi baixado corretamente
      - run: aws s3 cp index.html s3://$BUCKET_S3 --acl public-read --region us-east-1
on:
  # push:
  #  branches: [main]
  workflow_dispatch
  

