name: pipeline-deploy-s3
on:
  push:
    branches: [ main ]  # O pipeline será acionado em pushes para o branch "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # Faz o checkout do repositório para que o GitHub Actions tenha acesso aos arquivos

      - name: Install pandoc
        run: sudo apt-get install pandoc  # Instala o pandoc para conversão de markdown para HTML

      - name: Convert README.md to HTML
        run: pandoc README.md -f markdown -t html -s -o index.html  # Converte o README.md para HTML

      - name: List files (optional)
        run: ls -la  # Lista os arquivos gerados (opcional, para ver o que está acontecendo)

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Faz o upload do arquivo HTML como artefato para ser reutilizado na próxima etapa
        with:
          name: site
          path: index.html

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Depende do job "build" ter sucesso
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_EC2_METADATA_DISABLED: true
      BUCKET_S3: conchayoro-psm  # Substitua pelo nome correto do seu bucket S3
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4  # Baixa o artefato gerado na etapa anterior
        with:
          name: site
          path: .

      - name: List files (optional)
        run: ls -la  # Lista os arquivos baixados (opcional, para depuração)

      - name: Upload to S3
        run: aws s3 cp index.html s3://$BUCKET_S3 --acl public-read  # Faz o upload do HTML para o bucket S3 com permissão pública
